import React, { useEffect, useState } from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import { convertToMMYY, formatDate } from '@/lib/date/format';
import { spellMoney } from '@/lib/money/spell';
import QRCode from 'qrcode';

interface PaymentProps {
  id: string
  amount: string
  description: string
  transactionDate: string
  transactionNumber: string
  name: string
  city: string
  address: string
  companyName: string
  staff: string
}

const customPageSize = {
  width: 841,
  height: 595,
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    paddingHorizontal: 80,
    paddingVertical: 30,
  },
  section: {
    flexGrow: 1,
  },
  divider: {
    marginTop: 25,
  },
  footer: {
    marginBottom: 15,
    fontSize: 8,
    textAlign: 'center',
    color: 'grey',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    textDecoration: 'underline',
    fontWeight: 'bold',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12,
    textAlign: 'center',
  },
  signatureDate: {
    marginTop: 16,
    fontSize: 14,
    textAlign: 'justify',
  },
  column: {
    flexDirection: 'column',
  },
  row: {
    flexDirection: 'row',
    flexGrow: 1,
    justifyContent: 'space-between',
    marginTop: 30,
  },
  amount: {
    marginVertical: 4,
    fontSize: 20,
    textAlign: 'left',
    border: 1,
    padding: 12,
    fontWeight: 'bold',
  },
  signature: {
    marginVertical: 4,
    marginTop: 100,
    fontSize: 14,
    textAlign: 'justify',
  },
  tableCell: {
    flexDirection: 'row',
    marginVertical: 4,
    fontSize: 14,
    textAlign: 'left',
  },
  text1: {
    flexBasis: '200px',
  },
  text2: {
    flexBasis: '20px',
  },
  text3: {
    flexBasis: '500px',
    fontSize: 14,
    textAlign: 'justify',
  },
  letterhead: {
    paddingBottom: 10,
    marginBottom: 20,
    borderBottom: 1,
  },
  letterTitle: {
    marginTop: 4,
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  letterSubtitle: {
    marginTop: 4,
    fontSize: 12,
    textAlign: 'center',
  },
  qrCode: {
    margin: 10,
    width: 100,
    height: 100,
  }
});

const InvoicePdf = ({ id, amount, description, transactionDate, transactionNumber, name, city, address, companyName, staff = 'Lorem Ipsum'}: PaymentProps) => {
  const [qrc, setQrc] = useState('');

  useEffect(() => {
    QRCode.toDataURL(`${window.location.origin}/invoice/${id}`)
      .then(setQrc)
      .catch(console.error);
  }, [id])
  
  return (
    <Document>
      <Page size={customPageSize} style={styles.page}>
        <View style={styles.section}>
          <View style={styles.letterhead}>
            <Text style={styles.letterTitle}>{companyName}</Text>
            <Text style={styles.letterSubtitle}>{address}</Text>
          </View>
          <Text style={styles.title}>BUKTI PEMBAYARAN</Text>
          <Text style={styles.subtitle}>No. {convertToMMYY(transactionDate)}-{transactionNumber}</Text>
          <View style={styles.divider}/>
          <View style={styles.section}>
            <View style={styles.tableCell}>
              <Text style={styles.text1}>Sudah terima dari</Text>
              <Text style={styles.text2}>:</Text>
              <Text style={styles.text3}>{name}</Text>
            </View>
            <View style={styles.tableCell}>
              <Text style={styles.text1}>Uang sejumlah</Text>
              <Text style={styles.text2}>:</Text>
              <Text style={styles.text3}>{spellMoney(parseInt(amount)).trim()} Rupiah</Text>
            </View>
            <View style={styles.tableCell}>
              <Text style={styles.text1}>Guna pembayaran</Text>
              <Text style={styles.text2}>:</Text>
              <Text style={styles.text3}>{description}</Text>
            </View>
            <View style={styles.row}>
              <View style={styles.column}>
                <Text style={styles.amount}>Rp. {amount.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')}</Text>
                {qrc ? (
                  <Image src={qrc} style={styles.qrCode} />
                ) : (
                  <Text></Text>
                )}
              </View>
              <View style={styles.column}>
                <Text style={styles.signatureDate}>{city}, {formatDate(transactionDate)}</Text>
                <Text style={styles.signature}>{staff}</Text>
              </View>
            </View>
            <Text style={styles.footer}>Auto Generated by KBIHU.id: {id}</Text>
          </View>
        </View>
      </Page>
    </Document>
  );
};

export default InvoicePdf;